CREATE TABLE order_info (
  id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  products               bigint[] NOT NULL,
  remarks                text,
  order_date             timestamptz
);
CREATE INDEX order_info__customer_id__idx ON order_info(customer_id);
